name: Deploy Docker container to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 커밋이 발생할 때 트리거

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_IP }} << 'EOF'
          cd /home/ec2-user/lol_park_police/
        
          git pull origin main
        
          if ! [ -x "$(command -v docker)" ]; then
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh
            sudo usermod -aG docker $USER
            newgrp docker  # 그룹 변경 사항 바로 적용
          fi
          
          # Docker 명령어에 sudo 추가
          sudo docker stop warning-container || true
          sudo docker rm warning-container || true
        
          sudo docker build -t warning-image .
        
          sudo docker run -d -p 81:80 --name warning-container \
            -e DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} \
            -v /home/ec2-user/database/warnings.db:/database/warnings.db \
            warning-image
        EOF
